export const AUTHORIZATION = 'AUTHORIZATION';
export const AUTHORIZATION_TRUE = 'AUTHORIZATION_TRUE';
export const AUTHORIZATION_FALSE = 'AUTHORIZATION_FALSE';

export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ACCOUNT_TRUE = 'GET_ACCOUNT_TRUE';
export const GET_ACCOUNT_FALSE = 'GET_ACCOUNT_FALSE';

export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_AVATAR_TRUE = 'CHANGE_AVATAR_TRUE';
export const CHANGE_AVATAR_FALSE = 'CHANGE_AVATAR_FALSE';

export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';