export const AUTHORIZATION = 'AUTHORIZATION';
export const AUTHORIZATION_TRUE = 'AUTHORIZATION_TRUE';
export const AUTHORIZATION_FALSE = 'AUTHORIZATION_FALSE';

export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ACCOUNT_TRUE = 'GET_ACCOUNT_TRUE';
export const GET_ACCOUNT_FALSE = 'GET_ACCOUNT_FALSE';

export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_AVATAR_TRUE = 'CHANGE_AVATAR_TRUE';
export const CHANGE_AVATAR_FALSE = 'CHANGE_AVATAR_FALSE';

export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_TRUE = 'GET_POSTS_TRUE'
export const GET_POSTS_FALSE = 'GET_POSTS_FALSE'

export const GET_ONE_POST = 'GET_ONE_POST';
export const GET_ONE_POST_TRUE = 'GET_ONE_POST_TRUE';
export const GET_ONE_POST_FALSE = 'GET_ONE_POST_FALSE';

export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_TRUE = 'ADD_COMMENT_TRUE';
export const ADD_COMMENT_FALSE = 'ADD_COMMENT_FALSE';

export const GET_NEW_COMMENTS = 'GET_NEW_COMMENTS';
export const GET_NEW_COMMENTS_TRUE = 'GET_NEW_COMMENTS_TRUE';
export const GET_NEW_COMMENTS_FALSE = 'GET_NEW_COMMENTS_FALSE';

export const LIKE_COMMENT = 'LIKE_COMMENT';
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT'; 

export const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
export const GET_PUBLICATIONS_TRUE = 'GET_PUBLICATIONS_TRUE';
export const GET_PUBLICATIONS_FALSE = 'GET_PUBLICATIONS_FALSE';

export const PUBLICATION_LIKE = 'PUBLICATION_LIKE';
export const PUBLICATION_UNLIKE = 'PUBLICATION_UNLIKE';
